# Generated by Django 6.1.1 on 2026-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('hidden', 'Hidden')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Mileage in kilometres.')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('body_type', models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('saloon', 'Saloon'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('pickup', 'Pickup'), ('van', 'Van'), ('bus', 'Bus')], default='suv', max_length=30)),
                ('drive_type', models.CharField(blank=True, max_length=50)),
                ('engine_size', models.CharField(blank=True, max_length=50)),
                ('exterior_color', models.CharField(blank=True, max_length=50)),
                ('interior_color', models.CharField(blank=True, max_length=50)),
                ('doors', models.PositiveIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
